name: final
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pillow
  - future
  - matplotlib
  - numpy
  - tensorboard>=1.14
  - pytorch=1.9.0
  - torchvision>=0.7.0
  - imageio
  - imageio-ffmpeg
  - av
  